- id: kgSurvey
  title: "Exploring knowledge graph-based neural-symbolic system from application perspective"
  venue: arXiv, 2024
  description: "This suvey paper explores KG-based neural-symbolic integration, enhancing neural reasoning, improving symbolic accuracy, and combining both"
  arxiv: 2405.03524
  image: reconfusion_before.png
  authors:
    - Shenzhe
    - Shengxiang
